### ISSUE TITLE
Unicode display problem

### ISSUE THREAD

**Issue by ncoghlan** [rfk/playitagainsam-js#1]
When I attempt to display this slide show in Firefox, the final line of output in the demo comes up as an empty string rather than the expected text:
https://bitbucket.org/ncoghlan/misc/src/default/talks/2012-pyconindia/py3.3-highlights/theme/demo-js/unicode_size.js

I thought it might be a font problem, but I changed the theme CSS to favour "Monospace" (the same font used by Konsole), with no joy.

**Comment by rfk** [comment]
Thanks for the report Nick; closing these old issues as I move the project into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
