### ISSUE TITLE
Scrollbar not working

### ISSUE THREAD

**Issue by ncoghlan** [rfk/playitagainsam-js#2]
In my current slides, the scrollbar isn't working when embedded in a landslide presentation.

The scrollbar appears but is not responsive in any way.

Really noticed for https://bitbucket.org/ncoghlan/misc/changeset/e56896d3f72c8c52253ba705e23a1f1c7f83044d (since some of those tracebacks don't fit on the screen all at once)

My web-fu isn't up to figuring it out at this point - I'll probably just do this particular demo in the terminal instead (talk is in ~8 hours - entirely my own fault for not getting started sooner!).

**Comment by rfk** [comment]
Thanks for the report Nick; closing these old issues as I move the project into archive mode:

  https://rfk.id.au/blog/entry/archiving-open-source-projects/
